export const gPieces = {
  KING_WHITE: 'K',
  KING_BLACK: 'k',
  BISHOP_WHITE: 'B',
  BISHOP_BLACK: 'b',
  PAWN_WHITE: 'P',
  PAWN_BLACK: 'p',
  QUEEN_WHITE: 'Q',
  QUEEN_BLACK: 'q',
  ROOK_WHITE: 'R',
  ROOK_BLACK: 'r',
  KNIGHT_WHITE: 'N',
  KNIGHT_BLACK: 'n',
}
// export const gPieces = {
//   KING_WHITE: '♔',
//   KING_BLACK: '♚',
//   BISHOP_WHITE: '♗',
//   BISHOP_BLACK: '♝',
//   PAWN_WHITE: '♙',
//   PAWN_BLACK: '♟',
//   QUEEN_WHITE: '♕',
//   QUEEN_BLACK: '♛',
//   ROOK_WHITE: '♖',
//   ROOK_BLACK: '♜',
//   KNIGHT_WHITE: '♘',
//   KNIGHT_BLACK: '♞',
// }
